server:
  port: 8081

spring:
  application:
    name: MOVIE-SERVICE
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  tracing:                                              # ✅ add this
    sampling:
      probability: 1.0
  zipkin:                                               # ✅ add this
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    root: INFO